apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-1
  template:
    metadata:
      labels:
        app: nginx-app-1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-app-1-service
spec:
  selector:
    app: nginx-app-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
